// action types
export default {
  ADD_POST: 'ADD_POST',
  RESET_INPUT: 'RESET_INPUT',
  UPDATE_INPUT: 'UPDATE_INPUT',

  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER'
};
